# All possible images can be seen at https://github.com/devcontainers/images/tree/main/src/javascript-node,
# though that doesn't appear to show which debian aligns with which version name,
# but that can be found at https://wiki.debian.org/LTS
#
# Update 'VARIANT' to pick a Node version: 20, 18, 16
# -Debian version: bookworm (12), bullseye (11), buster (10)
ARG VARIANT=20-bookworm
FROM mcr.microsoft.com/devcontainers/typescript-node:1-${VARIANT}